PSPSDK: debug/callstack.c File Reference
callstack.c File Reference
#include "pspdebug.h"
Data Structures
struct _returnCache
Macros
#define RESTORE_RETURNVAL 0x8fbf0000
#define RESTORE_RETURNVAL_MASK 0xffff0000
#define RESTORE_RETURNVAL2 0xdfbf0000
#define RESTORE_RETURNVAL3 0x7bbf0000
#define ADJUST_STACKP_C 0x27bd0000
#define ADJUST_STACKP_C_MASK 0xffff0000
#define ADJUST_STACKP_V 0x03a1e821
#define ADJUST_STACKP_V_MASK 0xffffffff
#define SET_UPPER_C 0x3c010000
#define SET_UPPER_C_MASK 0xffff0000
#define OR_LOWER_C 0x34210000
#define OR_LOWER_C_MASK 0xffff0000
#define SET_LOWER_C 0x34010000
#define SET_LOWER_C_MASK 0xffff0000
#define RETURN 0x03e00008
#define CALL(f) (0x0c000000 | (((int) (f)) >> 2))
#define HASH_SIZE 256
#define HASH(ra) ((((int) (ra)) >> 2) & (HASH_SIZE - 1))
#define TRUE 1
#define FALSE 0
Typedefs
typedef struct _returnCache ReturnCacheRec
typedef struct _returnCache * ReturnCachePtr
typedef int Bool
Functions
unsigned int * pspGetReturnAddress ()
unsigned int * pspGetStackPointer ()
int main ()
int pspDebugGetStackTrace (unsigned int *results, int max)
Get a MIPS stack trace (might work :P)
Macro Definition Documentation
ADJUST_STACKP_C
#define ADJUST_STACKP_C 0x27bd0000
ADJUST_STACKP_C_MASK
#define ADJUST_STACKP_C_MASK 0xffff0000
ADJUST_STACKP_V
#define ADJUST_STACKP_V 0x03a1e821
ADJUST_STACKP_V_MASK
#define ADJUST_STACKP_V_MASK 0xffffffff
CALL
#define CALL (f) (0x0c000000 | (((int) (f)) >> 2))
FALSE
#define FALSE 0
HASH
#define HASH (ra) ((((int) (ra)) >> 2) & (HASH_SIZE - 1))
HASH_SIZE
#define HASH_SIZE 256
OR_LOWER_C
#define OR_LOWER_C 0x34210000
OR_LOWER_C_MASK
#define OR_LOWER_C_MASK 0xffff0000
RESTORE_RETURNVAL
#define RESTORE_RETURNVAL 0x8fbf0000
RESTORE_RETURNVAL2
#define RESTORE_RETURNVAL2 0xdfbf0000
RESTORE_RETURNVAL3
#define RESTORE_RETURNVAL3 0x7bbf0000
RESTORE_RETURNVAL_MASK
#define RESTORE_RETURNVAL_MASK 0xffff0000
RETURN
#define RETURN 0x03e00008
SET_LOWER_C
#define SET_LOWER_C 0x34010000
SET_LOWER_C_MASK
#define SET_LOWER_C_MASK 0xffff0000
SET_UPPER_C
#define SET_UPPER_C 0x3c010000
SET_UPPER_C_MASK
#define SET_UPPER_C_MASK 0xffff0000
TRUE
#define TRUE 1
Typedef Documentation
Bool
typedef int Bool
ReturnCachePtr
typedef struct _returnCache * ReturnCachePtr
ReturnCacheRec
typedef struct _returnCache ReturnCacheRec
Function Documentation
main()
int main ()
Referenced by pspDebugGetStackTrace().
pspDebugGetStackTrace()
int pspDebugGetStackTrace (unsigned int * results, int max)
Get a MIPS stack trace (might work :P)
Parameters
results - List of points to store the results of the trace, (up to max)
max - Maximum number of back traces
Returns
The number of frames stored in results.
References CALL, main(), pspGetReturnAddress(), pspGetStackPointer(), ra, and sp.
pspGetReturnAddress()
unsigned int* pspGetReturnAddress ()
Referenced by pspDebugGetStackTrace().
pspGetStackPointer()
unsigned int* pspGetStackPointer ()
Referenced by pspDebugGetStackTrace().