var modules =
[
    [ "User Audio Library", "group__Audio.html", null ],
    [ "Debug Utility Library", "group__Debug.html", null ],
    [ "Graphics Utility Library", "group__GU.html", null ],
    [ "Hprm Remote", "group__Hprm.html", null ],
    [ "Interface to the sceIdStorage_driver library.", "group__IdStorage.html", null ],
    [ "Interrupt Manager Kernel", "group__IntrManKern.html", null ],
    [ "Driver interface to IoFileMgr", "group__IoFileMgr__Kernel.html", null ],
    [ "Interface to the KDebugForKernel library.", "group__Kdebug.html", null ],
    [ "Interface to the LoadCoreForKernel library.", "group__LoadCore.html", null ],
    [ "Interface to the LoadExecForKernel library.", "group__LoadExecKernel.html", null ],
    [ "Kernel Module Manager Library", "group__ModuleMgrKern.html", null ],
    [ "Driver interface to Stdio", "group__Stdio__Kernel.html", null ],
    [ "Interface to the sceSyscon_driver library.", "group__Syscon.html", null ],
    [ "System Memory Manager Kernel", "group__SysMemKern.html", null ],
    [ "Interface to the sceSysreg_driver library.", "group__Sysreg.html", null ],
    [ "Thread Manager kernel functions", "group__ThreadmanKern.html", null ],
    [ "PSPSDK Utility Library", "group__PSPSDK.html", null ],
    [ "Integrated Remote Control System Library", "group__Sony.html", null ],
    [ "Interrupt Manager", "group__IntrMan.html", null ],
    [ "File IO Library", "group__FileIO.html", null ],
    [ "LoadExec Library", "group__LoadExec.html", null ],
    [ "Module Manager Library", "group__ModuleMgr.html", null ],
    [ "Stdio Library", "group__Stdio.html", null ],
    [ "System Memory Manager", "group__SysMem.html", null ],
    [ "Thread Manager Library", "group__ThreadMan.html", null ],
    [ "Utils Library", "group__Utils.html", null ],
    [ "Chnnlsv Library", "group__Chnnlsv.html", null ],
    [ "Controller Kernel Library", "group__Ctrl.html", null ],
    [ "Registry Kernel Library", "group__Reg.html", null ],
    [ "UMD Kernel Library", "group__UMD.html", null ]
];