PSPSDK: debug/profiler.c File Reference
profiler.c File Reference
#include <pspkernel.h>
#include <pspdebug.h>
Macros
#define PROFILER_REG_BASE 0xBC400000
#define PROFILER_REG_COUNT 21
Functions
void pspDebugProfilerEnable (void)
Enables the profiler hardware.
void pspDebugProfilerDisable (void)
Disables the profiler hardware.
void pspDebugProfilerClear (void)
Clear the profiler registers.
void pspDebugProfilerGetRegs (PspDebugProfilerRegs *regs)
Get the profiler register state.
void pspDebugProfilerPrint (void)
Print the profiler registers to screen.
Macro Definition Documentation
PROFILER_REG_BASE
#define PROFILER_REG_BASE 0xBC400000
PROFILER_REG_COUNT
#define PROFILER_REG_COUNT 21
Function Documentation
pspDebugProfilerClear()
void pspDebugProfilerClear (void)
Clear the profiler registers.
References i, PROFILER_REG_BASE, and PROFILER_REG_COUNT.
pspDebugProfilerDisable()
void pspDebugProfilerDisable (void)
Disables the profiler hardware.
pspDebugProfilerEnable()
void pspDebugProfilerEnable (void)
Enables the profiler hardware.
pspDebugProfilerGetRegs()
void pspDebugProfilerGetRegs (PspDebugProfilerRegs * regs)
Get the profiler register state.
Parameters
regs - A pointer to a PspDebugProfilerRegs structure.
References i, NULL, PROFILER_REG_BASE, and PROFILER_REG_COUNT.
Referenced by pspDebugProfilerPrint().
pspDebugProfilerPrint()
void pspDebugProfilerPrint (void)
Print the profiler registers to screen.
References _PspDebugProfilerRegs::bus_access, _PspDebugProfilerRegs::cached_load, _PspDebugProfilerRegs::cached_store, _PspDebugProfilerRegs::cop0_inst, _PspDebugProfilerRegs::copz, _PspDebugProfilerRegs::cpuck, _PspDebugProfilerRegs::d_miss, _PspDebugProfilerRegs::d_writeback, _PspDebugProfilerRegs::enable, _PspDebugProfilerRegs::fpu_inst, _PspDebugProfilerRegs::i_miss, _PspDebugProfilerRegs::internal, _PspDebugProfilerRegs::local_bus, _PspDebugProfilerRegs::memory, pspDebugProfilerGetRegs(), pspDebugScreenPrintf(), _PspDebugProfilerRegs::sleep, _PspDebugProfilerRegs::systemck, _PspDebugProfilerRegs::uncached_load, _PspDebugProfilerRegs::uncached_store, _PspDebugProfilerRegs::vfpu, and _PspDebugProfilerRegs::vfpu_inst.