PSPSDK: prof/pspprof.h File Reference
pspprof.h File Reference
Functions
void gprof_cleanup ()
Writes gmon.out dump file and stops profiling.
Function Documentation
gprof_cleanup()
void gprof_cleanup ()
Writes gmon.out dump file and stops profiling.
Called from atexit() handler; will dump out a host:gmon.out file with all collected information.
References fclose(), fopen(), fp, fwrite(), GMON_PROF_OFF, GMON_PROF_ON, GMONVERSION, gp, gmonhdr::hpc, i, gmonhdr::lpc, gmonhdr::ncnt, gmonhdr::profrate, gmonhdr::resv, SAMPLE_FREQ, sceKernelStopVTimer(), and gmonhdr::version.