PSPSDK: sdk/query_mod.c File Reference
query_mod.c File Reference
#include <pspkerneltypes.h>
#include <psploadcore.h>
#include <pspmodulemgr.h>
#include <pspmodulemgr_kernel.h>
#include <pspsdk.h>
#include <string.h>
Functions
int pspSdkGetModuleIdList (SceUID *readbuf, int readbufsize, int *idcount)
Get the list of module IDs.
int pspSdkQueryModuleInfoV1 (SceUID uid, SceKernelModuleInfo *modinfo)
Query a modules information from its uid.
Function Documentation
pspSdkGetModuleIdList()
int pspSdkGetModuleIdList (SceUID * readbuf, int readbufsize, int * idcount)
Get the list of module IDs.
Note
This is a replacement function for the missing v1.5 sceKernelGetModuleIdList on v1.0 firmware. DO NOT use on anything above that version.
Parameters
readbuf - Buffer to store the module list.
readbufsize - Number of elements in the readbuffer.
idcount - Returns the number of module ids
Returns
>= 0 on success
References sceKernelGetModuleList(), and sceKernelModuleCount().
pspSdkQueryModuleInfoV1()
int pspSdkQueryModuleInfoV1 (SceUID uid, SceKernelModuleInfo * modinfo)
Query a modules information from its uid.
Note
this is a replacement function for the broken kernel sceKernelQueryModuleInfo in v1.0 firmware DO NOT use on a anything above that version. This also needs kernel mode access where the normal one has a user mode stub.
Parameters
uid - The UID of the module to query.
modinfo - Pointer a module SceKernelModuleInfo structure.
Returns
< 0 on error.
References SceModule::attribute, SceKernelModuleInfo::attribute, SceModule::bss_size, SceKernelModuleInfo::bss_size, SceModule::data_size, SceKernelModuleInfo::data_size, SceModule::entry_addr, SceKernelModuleInfo::entry_addr, SceModule::gp_value, SceKernelModuleInfo::gp_value, memcpy(), SceModule::modname, SceKernelModuleInfo::name, SceModule::nsegment, SceKernelModuleInfo::nsegment, NULL, sceKernelFindModuleByUID(), SceModule::segmentaddr, SceKernelModuleInfo::segmentaddr, SceModule::segmentsize, SceKernelModuleInfo::segmentsize, SceModule::text_addr, SceKernelModuleInfo::text_addr, SceModule::text_size, SceKernelModuleInfo::text_size, SceModule::version, and SceKernelModuleInfo::version.