PSPSDK: gu/sceGuInit.c File Reference
sceGuInit.c File Reference
#include "guInternal.h"
#include <pspkernel.h>
#include <pspge.h>
#include <pspdisplay.h>
Functions
unsigned int __attribute__ ((aligned(16)))
void sceGuInit (void)
Initalize the GU system.
Function Documentation
__attribute__()
unsigned int __attribute__ ((aligned(16)))
sceGuInit()
void sceGuInit (void)
Initalize the GU system.
This function MUST be called as the first function, otherwise state is undetermined.
References callbackFin(), callbackSig(), PspGeCallbackData::finish_arg, PspGeCallbackData::finish_func, GuSettings::ge_callback_id, ge_edram_address, ge_list_executed, gu_settings, GuSettings::kernel_event_flag, PSP_DISPLAY_SETBUF_IMMEDIATE, resetValues(), sceGeEdramGetAddr(), sceGeListEnQueue(), sceGeListSync(), sceGeSetCallback(), sceKernelCreateEventFlag(), PspGeCallbackData::signal_arg, PspGeCallbackData::signal_func, GuSettings::swapBuffersBehaviour, and GuSettings::swapBuffersCallback.