PSPSDK: gu/sceGuFinish.c File Reference
sceGuFinish.c File Reference
#include "guInternal.h"
Functions
int sceGuFinish (void)
Finish current display list and go back to the parent context.
int sceGuFinishId (unsigned int id)
Finish current display list and go back to the parent context, sending argument id for the finish callback.
Function Documentation
sceGuFinish()
int sceGuFinish (void)
Finish current display list and go back to the parent context.
If the context is GU_DIRECT, the stall-address is updated so that the entire list will execute. Otherwise, only the terminating action is written to the list, depending on context-type.
The finish-callback will get a zero as argument when using this function.
This also restores control back to whatever context that was active prior to this call.
Returns
Size of finished display list
References GuDisplayList::current, GU_CALL, gu_call_mode, gu_contexts, gu_curr_context, GU_DIRECT, gu_list, GU_SEND, GuContext::list, GuDisplayList::parent_context, sendCommandi(), sendCommandiStall(), size, and GuDisplayList::start.
sceGuFinishId()
int sceGuFinishId (unsigned int id)
Finish current display list and go back to the parent context, sending argument id for the finish callback.
If the context is GU_DIRECT, the stall-address is updated so that the entire list will execute. Otherwise, only the terminating action is written to the list, depending on context-type.
Parameters
id - Finish callback id (16-bit)
Returns
Size of finished display list
References GuDisplayList::current, GU_CALL, gu_call_mode, gu_contexts, gu_curr_context, GU_DIRECT, gu_list, GU_SEND, GuContext::list, GuDisplayList::parent_context, sendCommandi(), sendCommandiStall(), size, and GuDisplayList::start.