PSPSDK: gu/sceGuDisable.c File Reference
sceGuDisable.c File Reference
#include "guInternal.h"
Functions
void sceGuDisable (int state)
Disable GE state.
Function Documentation
sceGuDisable()
void sceGuDisable (int state)
Disable GE state.
Look at sceGuEnable() for a list of states
Parameters
state - Which state to disable
References GuContext::fragment_2x, GU_ALPHA_TEST, GU_BLEND, GU_CLIP_PLANES, GU_COLOR_LOGIC_OP, GU_COLOR_TEST, gu_contexts, GU_CULL_FACE, gu_curr_context, GU_DEPTH_TEST, GU_DITHER, gu_draw_buffer, GU_FACE_NORMAL_REVERSE, GU_FOG, GU_FRAGMENT_2X, GU_LIGHT0, GU_LIGHT1, GU_LIGHT2, GU_LIGHT3, GU_LIGHTING, GU_LINE_SMOOTH, GU_PATCH_CULL_FACE, GU_PATCH_FACE, GU_SCISSOR_TEST, gu_states, GU_STENCIL_TEST, GU_TEXTURE_2D, GuDrawBuffer::height, GuContext::scissor_enable, sendCommandi(), GuContext::texture_function, and GuDrawBuffer::width.
Referenced by sceGuSetAllStatus(), and sceGuSetStatus().