PSPSDK: gu/sceGuDispBuffer.c File Reference
sceGuDispBuffer.c File Reference
#include "guInternal.h"
#include <pspkernel.h>
#include <pspdisplay.h>
Functions
void drawRegion (int x, int y, int width, int height)
void sceGuDispBuffer (int width, int height, void *dispbp, int dispbw)
Set display buffer parameters.
Function Documentation
drawRegion()
void drawRegion (int x, int y, int width, int height)
References sendCommandi(), x, and y.
Referenced by sceGuDispBuffer().
sceGuDispBuffer()
void sceGuDispBuffer (int width, int height, void * dispbp, int dispbw)
Set display buffer parameters.
Example: Setup a standard 16-bit display buffer
sceGuDispBuffer(480,272,(void*)512*272*2,512); // 480*272, skipping the draw buffer located at address 0
Parameters
width - Width of the display buffer in pixels
height - Width of the display buffer in pixels
dispbp - VRAM pointer to where the display-buffer starts
dispbw - Display buffer width (block aligned)
References GuDrawBuffer::disp_buffer, drawRegion(), GuDrawBuffer::frame_width, ge_edram_address, gu_display_on, gu_draw_buffer, GuDrawBuffer::height, GuDrawBuffer::pixel_size, PSP_DISPLAY_SETBUF_NEXTFRAME, sceDisplaySetFrameBuf(), sceDisplaySetMode(), and GuDrawBuffer::width.