PSPSDK: gu/sceGuEnable.c File Reference
sceGuEnable.c File Reference
#include "guInternal.h"
Functions
void sceGuEnable (int state)
Enable GE state.
Function Documentation
sceGuEnable()
void sceGuEnable (int state)
Enable GE state.
The currently available states are:
GU_ALPHA_TEST
GU_DEPTH_TEST
GU_SCISSOR_TEST
GU_BLEND
GU_CULL_FACE
GU_DITHER
GU_CLIP_PLANES
GU_TEXTURE_2D
GU_LIGHTING
GU_LIGHT0
GU_LIGHT1
GU_LIGHT2
GU_LIGHT3
GU_COLOR_LOGIC_OP
Parameters
state - Which state to enable
References GuContext::fragment_2x, GU_ALPHA_TEST, GU_BLEND, GU_CLIP_PLANES, GU_COLOR_LOGIC_OP, GU_COLOR_TEST, gu_contexts, GU_CULL_FACE, gu_curr_context, GU_DEPTH_TEST, GU_DITHER, GU_FACE_NORMAL_REVERSE, GU_FOG, GU_FRAGMENT_2X, GU_LIGHT0, GU_LIGHT1, GU_LIGHT2, GU_LIGHT3, GU_LIGHTING, GU_LINE_SMOOTH, GU_PATCH_CULL_FACE, GU_PATCH_FACE, GU_SCISSOR_TEST, gu_states, GU_STENCIL_TEST, GU_TEXTURE_2D, GuContext::scissor_enable, GuContext::scissor_end, GuContext::scissor_start, sendCommandi(), and GuContext::texture_function.
Referenced by sceGuSetAllStatus(), and sceGuSetStatus().