PSPSDK: gu/sceGuClear.c File Reference
sceGuClear.c File Reference
#include "guInternal.h"
Functions
void sceGuClear (int flags)
Clear current drawbuffer.
Function Documentation
sceGuClear()
void sceGuClear (int flags)
Clear current drawbuffer.
Available clear-flags are (OR them together to get final clear-mode):
GU_COLOR_BUFFER_BIT - Clears the color-buffer
GU_STENCIL_BUFFER_BIT - Clears the stencil-buffer
GU_DEPTH_BUFFER_BIT - Clears the depth-buffer
Parameters
flags - Which part of the buffer to clear
References GuContext::clear_color, GuContext::clear_depth, GuContext::clear_stencil, flags, GU_COLOR_8888, GU_COLOR_BUFFER_BIT, gu_contexts, gu_curr_context, GU_DEPTH_BUFFER_BIT, gu_draw_buffer, GU_FAST_CLEAR_BIT, GU_SPRITES, GU_STENCIL_BUFFER_BIT, GU_TRANSFORM_2D, GU_VERTEX_16BIT, GuDrawBuffer::height, i, GuDrawBuffer::pixel_size, sceGuDrawArray(), sceGuGetMemory(), sendCommandi(), GuDrawBuffer::width, x, y, and z.