PSPSDK: debug/sio.c File Reference
sio.c File Reference
#include <pspkernel.h>
#include <pspdebug.h>
#include <pspsyscon.h>
Macros
#define PSP_UART4_FIFO 0xBE500000
#define PSP_UART4_STAT 0xBE500018
#define PSP_UART4_DIV1 0xBE500024
#define PSP_UART4_DIV2 0xBE500028
#define PSP_UART4_CTRL 0xBE50002C
#define PSP_UART_CLK 96000000
#define PSP_UART_TXFULL 0x20
#define PSP_UART_RXEMPTY 0x10
Functions
int sceHprmEnd (void)
int sceSysregUartIoEnable (int uart)
void pspDebugSioPutchar (int ch)
Put a character to the remote sio.
int pspDebugSioGetchar (void)
Get a character from the remote sio.
void pspDebugSioPuts (const char *str)
Write a string to the sio port.
int pspDebugSioPutData (const char *data, int len)
Write a set of data to the sio port.
int pspDebugSioPutText (const char *data, int len)
Write a set of data to the sio port converting single line feeds to CRLF and single CR to CRLF.
void pspDebugSioSetBaud (int baud)
Set the baud rate of the SIO, e.g.
void pspDebugSioInit (void)
Initialise the remote SIO port (defaults to 4800 8N1).
void pspDebugEnablePutchar (void)
Enable debug character output.
void pspDebugSioInstallKprintf (void)
Install a kprintf debug putchar handler.
void pspDebugSioEnableKprintf (void)
Enable the kprintf handler (once installed)
void pspDebugSioDisableKprintf (void)
Disable the kprintf handler (once installed)
Variables
u32 sceKernelRemoveByDebugSection
Macro Definition Documentation
PSP_UART4_CTRL
#define PSP_UART4_CTRL 0xBE50002C
PSP_UART4_DIV1
#define PSP_UART4_DIV1 0xBE500024
PSP_UART4_DIV2
#define PSP_UART4_DIV2 0xBE500028
PSP_UART4_FIFO
#define PSP_UART4_FIFO 0xBE500000
PSP_UART4_STAT
#define PSP_UART4_STAT 0xBE500018
PSP_UART_CLK
#define PSP_UART_CLK 96000000
PSP_UART_RXEMPTY
#define PSP_UART_RXEMPTY 0x10
PSP_UART_TXFULL
#define PSP_UART_TXFULL 0x20
Function Documentation
pspDebugEnablePutchar()
void pspDebugEnablePutchar (void)
Enable debug character output.
Needs to be called in order for the default Kprintf handler to work.
Referenced by pspDebugSioInstallKprintf().
pspDebugSioDisableKprintf()
void pspDebugSioDisableKprintf (void)
Disable the kprintf handler (once installed)
pspDebugSioEnableKprintf()
void pspDebugSioEnableKprintf (void)
Enable the kprintf handler (once installed)
pspDebugSioGetchar()
int pspDebugSioGetchar (void)
Get a character from the remote sio.
Returns
The character read or -1 if no characters available.
Referenced by getDebugChar().
pspDebugSioInit()
void pspDebugSioInit (void)
Initialise the remote SIO port (defaults to 4800 8N1).
Note
will delay 2 seconds to wait for the power to come up.
References sceHprmEnd(), sceKernelDelayThread(), sceSysconCtrlHRPower(), and sceSysregUartIoEnable().
pspDebugSioInstallKprintf()
void pspDebugSioInstallKprintf (void)
Install a kprintf debug putchar handler.
Implicitly calls pspDebugEnablePutchar so you do not need to call it explicitly. Sio must be initialised before calling this function however.
References pspDebugEnablePutchar(), and sceKernelRegisterDebugPutchar().
pspDebugSioPutchar()
void pspDebugSioPutchar (int ch)
Put a character to the remote sio.
Parameters
ch - Character to write.
Referenced by pspDebugSioPutData(), pspDebugSioPuts(), pspDebugSioPutText(), and putDebugChar().
pspDebugSioPutData()
int pspDebugSioPutData (const char * data, int len)
Write a set of data to the sio port.
Parameters
data - Pointer to the data to send.
len - Length of the data.
Returns
Number of characters written.
References i, and pspDebugSioPutchar().
pspDebugSioPuts()
void pspDebugSioPuts (const char * str)
Write a string to the sio port.
Parameters
str - String to write.
References pspDebugSioPutchar().
pspDebugSioPutText()
int pspDebugSioPutText (const char * data, int len)
Write a set of data to the sio port converting single line feeds to CRLF and single CR to CRLF.
Parameters
data - Pointer to the data to send.
len - Length of the data.
Returns
Number of characters written.
References i, and pspDebugSioPutchar().
pspDebugSioSetBaud()
void pspDebugSioSetBaud (int baud)
Set the baud rate of the SIO, e.g.
4800/9600..115200.
Parameters
baud - The baudrate to set.
References PSP_UART_CLK.
sceHprmEnd()
int sceHprmEnd (void)
Referenced by pspDebugSioInit().
sceSysregUartIoEnable()
int sceSysregUartIoEnable (int uart)
Referenced by pspDebugSioInit().
Variable Documentation
sceKernelRemoveByDebugSection
u32 sceKernelRemoveByDebugSection