PSPSDK: debug/stacktrace.c File Reference
stacktrace.c File Reference
#include <pspkernel.h>
#include <pspdebug.h>
#include <string.h>
Macros
#define CALL 0x0C000000
#define CALL_MASK 0xFC000000
#define IS_CALL(x) (((x) & CALL_MASK) == CALL)
#define CALL_ADDR(x) (((x) & ~CALL_MASK) << 2)
#define ELF_START (&_ftext)
#define ELF_END (&_etext)
Functions
int pspDebugGetStackTrace2 (PspDebugRegBlock *regs, PspDebugStackTrace *trace, int max)
Do a stack trace from the current exception.
Variables
u32 _ftext
u32 _etext
Macro Definition Documentation
CALL
#define CALL 0x0C000000
CALL_ADDR
#define CALL_ADDR (x) (((x) & ~CALL_MASK) << 2)
CALL_MASK
#define CALL_MASK 0xFC000000
ELF_END
#define ELF_END (&_etext)
ELF_START
#define ELF_START (&_ftext)
IS_CALL
#define IS_CALL (x) (((x) & CALL_MASK) == CALL)
Function Documentation
pspDebugGetStackTrace2()
int pspDebugGetStackTrace2 (PspDebugRegBlock * regs, PspDebugStackTrace * trace, int max)
Do a stack trace from the current exception.
Note
This function really isn't too general purpose and it is more than likely to generate a few false positives but I consider that better then missing out calls entirely. You have to use your discretion, your code and a objdump to work out if some calls are completely surprious or not ;)
Parameters
regs - Pointer to a register block from an exception.
trace - Pointer to an array of PspDebugStackTrace structures.
max - The maximum number of traces to make.
Returns
The number of functions found.
References memset(), NULL, _PspDebugRegBlock::r, sceKernelGetThreadId(), sceKernelReferThreadStatus(), SceKernelThreadInfo::size, SceKernelThreadInfo::stack, and SceKernelThreadInfo::stackSize.
Variable Documentation
_etext
u32 _etext
_ftext
u32 _ftext